# Generated by Django 5.1.1 on 2024-10-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='facebook_url',
            new_name='telegram_url',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='instagram_url',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='token',
            name='linkedin_url',
        ),
    ]
